# Generated by Django 4.1.5 on 2023-02-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_modelo3'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Modelo1',
        ),
    ]
