# Generated by Django 4.1.5 on 2023-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_delete_modelo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='apellido',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombre',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
